sudo: false
language: ruby
rvm:
  - 2.4.1
before_install:
  - openssl aes-256-cbc -K $encrypted_226ee2a1742f_key -iv $encrypted_226ee2a1742f_iv -in .fortnite_api_config.yml.enc -out spec/.fortnite_api_config.yml -d
  - gem install bundler -v 1.16.1
